Feat/rework planner
umdlife/navigation2 pull request #3
Opened 2021-05-10 08:36 UTC by ashwinsushil

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Ticket not created  |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | Drone + RP4 |

---

## Description of contribution in a few bullet points
* This PR adds support for GPS in the planner server
* A new message type called ComputePose which supports GeoPoseStamped and GeoPath
* ComputePose supports PoseStamped and Nav_msgs/Path
* New return type Nav2_msgs/PathAndBoundary to support planners like CoveragePlanner
* Function overloaded createPlan method on the GlobalPlanner to support GPS goals 
* Rework Nav2_navfn_planner to support the new GlobalPlanner
* Publish the path for visualization (A custom visualizer is made on the UnmannedLife side)

---

## Future work that may be required in bullet points

* Path visualizer on Rviz that supports GeoPath

2021-05-14 12:41 UTC, vicmassy requested changes

2021-05-14 12:41 UTC, vicmassy commented on nav2_planner/include/nav2_planner/planner_server.hpp
>     * @param goal goal request
I would include the updated description of the parameters

2021-05-14 13:53 UTC, ashwinsushil commented on nav2_planner/include/nav2_planner/planner_server.hpp
>     * @param goal goal request
resolved in 076a138

2021-05-20 08:23 UTC, vicmassy approved these changes
Awesome work! Let's keep it up  :100: :fire:

2021-05-20 08:23 UTC, vicmassy approved these changes

2021-07-12 09:08 UTC, merged